### ISSUE TITLE
(account|status).profile_emojis のレスポンスについて

### ISSUE THREAD

**Issue by rinsuki** [kiritan-pop/mastodon#1]
現状 https://github.com/kiritan-pop/mastodon/commit/4747e74170732384dd60a2c239cdbea4592e98f3 では、profile_emojis が 

```
{
    "@admin": {
      "account_id": "1",
      "url": "http://localhost:3000/avatars/original/missing.png",
      "account_url": "http://localhost:3000/@admin"
    }
}
```

のようになっていますが、先にこのプロパティを実装した dwango/mastodon では、

```
[
    {
        "shortcode": "@admin",
        "account_id": "1",
        "url": "http://localhost:3000/avatars/original/missing.png",
        "account_url": "http://localhost:3000/@admin"
    }
]
```

のようになっているため、一部のクライアントでprofile_emojisの解釈に失敗し、場合によってはクラッシュやエラーの発生を引き起こします。
できればフォーマットを friends.nico のものと揃えるか、あるいはプロパティ名を変更すると、うまく既存のものと被らずに行けると思います。

**Comment by kiritan-pop** [comment]
プロファイル名"profile_emojis"を"avatar_emojis"に変更しました。
ありがとうございます。
